#copied from bluedyn

substitutions:
  name: "geyserwise-tse"
  friendly_name: "Geyserwise TSE ESP Home"
  room: ""
  add_mac_suffix: "true"
  device_description: "Geyserwise TSE ESP Home"
  project_name: "BlueDyn.geyserwise-tse"
  project_version: "v1.0.0"
  sensor_update_interval: 10s
  dns_domain: ".local"
  timezone: ""
  sntp_update_interval: 6h
  sntp_server_1: "0.pool.ntp.org"
  sntp_server_2: "1.pool.ntp.org"
  sntp_server_3: "2.pool.ntp.org"  
  wifi_fast_connect: "false"
  log_level: "INFO"
  ipv6_enable: "false"
  web_server_version: "2"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  area: "${room}"  
  name_add_mac_suffix: "${add_mac_suffix}"
  min_version: 2024.6.0
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

dashboard_import:
  package_import_url: github://bluedyn/configs/geyserwise_tse.yaml
  import_full_config: false

preferences:
  flash_write_interval: 5min

api:
ota:
  - platform: esphome

mdns:
  disabled: false

web_server:
  port: 80
  version: ${web_server_version}

network:
  enable_ipv6: ${ipv6_enable}

wifi:
  ap: {}
  fast_connect: "${wifi_fast_connect}"
  domain: "${dns_domain}"

captive_portal:

uart:
  rx_pin: GPIO03
  tx_pin: GPIO01
  baud_rate: 9600

tuya:

sensor:
  - platform: "tuya"
    name: "Water Temperature"
    sensor_datapoint: 10
    unit_of_measurement: '°C'

  - platform: "tuya"
    name: "Element Runtime"
    sensor_datapoint: 107
    unit_of_measurement: 'hrs'

  - platform: "tuya"
    name: "Error Code"
    sensor_datapoint: 20

  - platform: "tuya"
    name: "Element Status"
    sensor_datapoint: 13

  - platform: uptime
    name: "Uptime Sensor"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
    disabled_by_default: true

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    id: wifi_percent
    filters:
      - lambda: |-
          return (x > -50) ? 100 : 
                 (x < -100) ? 0 : 
                 2 * (x + 100);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

number:  
  - platform: "tuya"
    name: "Block 1 00:00-06:00"
    number_datapoint: 103
    min_value: 30
    max_value: 65
    step: 1
    unit_of_measurement: '°C'

  - platform: "tuya"
    name: "Block 2 06:00-12:00"
    number_datapoint: 104
    min_value: 30
    max_value: 65
    step: 1
    unit_of_measurement: '°C'

  - platform: "tuya"
    name: "Block 3 12:00-18:00"
    number_datapoint: 105
    min_value: 30
    max_value: 65
    step: 1
    unit_of_measurement: '°C'

  - platform: "tuya"
    name: "Block 4 18:00-00:00"
    number_datapoint: 106
    min_value: 30
    max_value: 65
    step: 1
    unit_of_measurement: '°C'

  - platform: "tuya"
    name: "PTC Element Temp"
    number_datapoint: 102
    min_value: 30
    max_value: 85
    step: 1
    unit_of_measurement: '°C'

switch:
  - platform: "tuya"
    name: "Power"
    switch_datapoint: 1

  - platform: "tuya"
    name: "PTC Element Power"
    switch_datapoint: 101

select:
  - platform: "tuya"
    name: "Mode"
    enum_datapoint: 2
    optimistic: False
    options:
      0: "Holiday"
      1: "Normal"

button:
  - platform: restart
    id: "restart_device"
    name: "Restart"
    entity_category: "diagnostic"

  - platform: factory_reset
    id: device_Reset
    name: "Reset to Factory Default Settings"
    entity_category: diagnostic

  - platform: restart
    name: "Restart"
    id: device_restart
    entity_category: diagnostic

  - platform: safe_mode
    name: "Safe Mode"
    id: device_safe_mode
    internal: false
    entity_category: config

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      id: wifi_ip_address
      icon: mdi:ip-network
      entity_category: diagnostic
    ssid:
      name: "Connected SSID"
      id: wifi_connected_ssid
      icon: mdi:wifi-strength-2
      entity_category: diagnostic
    mac_address:
      name: "Mac Address"
      id: wifi_mac_address
      icon: mdi:network-pos
      entity_category: diagnostic

  - platform: template
    name: 'Last Restart'
    id: device_last_restart
    icon: mdi:clock
    entity_category: diagnostic

  - platform: template
    name: "Uptime"
    id: device_uptime
    entity_category: diagnostic
    lambda: |-
      int seconds = static_cast<int>(id(uptime_sensor).state);
      int days = seconds / 86400;
      seconds %= 86400;
      int hours = seconds / 3600;
      seconds %= 3600;
      int minutes = seconds / 60;
      seconds %= 60;

      if (days > 3650) {
        return {"Starting up"};
      } else if (days > 0) {
        return {str_sprintf("%dd %dh %dm %ds", days, hours, minutes, seconds)};
      } else if (hours > 0) {
        return {str_sprintf("%dh %dm %ds", hours, minutes, seconds)};
      } else if (minutes > 0) {
        return {str_sprintf("%dm %ds", minutes, seconds)};
      } else {
        return {str_sprintf("%ds", seconds)};
      }
    icon: mdi:clock-start

  - platform: template
    name: "Firmware Source"
    id: firmware_source
    icon: "mdi:code-tags"
    lambda: |-
      return {"GitHub: bluedyn/configs"};
    update_interval: 300s

time:
  - platform: sntp
    id: sntp_time
    timezone: "${timezone}"
    update_interval: ${sntp_update_interval}
    servers: 
      - "${sntp_server_1}"
      - "${sntp_server_2}"
      - "${sntp_server_3}"    
    on_time_sync:
      then:
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %I:%M:%S %p");'
